### ISSUE TITLE
please sync websockify

### ISSUE THREAD

**Issue by rpodgorny** [kanaka/noVNC#433]
lots of bugfixes there... ;-)

**Comment by DirectXMan12** [comment]
@kanaka, @samhed , @astrand : I think we need a better solution that just manually updating websockify every once and a while.  Probably the easiest way would be to make websockify a git submodule, and then have utils.sh and friends point to the correct location.  The other solution would just be to make having websockify installed be a dependency, and then provide a documentation/a script to automatically install it (e.g. optionally have `launch.sh` set up a Python venv and then install websockify into that).

What do you think?

**Comment by DirectXMan12** [comment]
speaking of which, a reverse sync might be in order (sync the new keysym.js and websock.js into websockify).

**Comment by kanaka** [comment]
@DirectXMan12 yeah, a better solution here would be good. My main priority was making sure that noVNC was as simple to check out and use as possible. git clone doesn't automatically pull down submodules, so I decided to sync manually. But you're right it is a hassle for sure. I think submodules (in order to support gh-pages) with a script to pull it down if it was missed the first time, would be the direction to go I think.

Speaking of which, at some point it would be good to push out a new version to the main gh-pages repo so that novnc.com gets the latest updates. Since gh-pages supports submodules, we just need to make sure that continues to work with whatever websockify solution we use.

**Comment by DirectXMan12** [comment]
>  git clone doesn't automatically pull down submodules, so I decided to sync manually.
`git clone --recursive` does.  But I get what you're saying.  I'll see if I can play around a bit and get a good solution working (we could do a `git submodule update --init --recursive` in `launch.sh` if we say websockify was missing, for instance)>

**Comment by kanaka** [comment]
@DirectXMan12 yeah, I think if launch.sh pulled down the submodules (maybe a separate script that it calls), and it's documented well on the README for first time users, that should work. The sync script should probably check if a file in the submodule exists before doing the update for cases where github isn't accessible ("Internet is down") the second time they run it and so that users who know what they are doing don't get their submodules automagically updated without their consent.

**Comment by DirectXMan12** [comment]
@kanaka : exactly what I was thinking.
