### ISSUE TITLE
messed up cursor coordinates when scrolled

### ISSUE THREAD

**Issue by rpodgorny** [kanaka/noVNC#459]
as of 2015-02-25, the git version behaves incorrectly:

when connected to a wide screen setup (two monitors), the scrollbar at the bottom appears. this is correct.

unfortunately, when it's used. the coordinates of the cursor on the target system do not match those displayed on the client. it seems to be something like 2x the offset.

reverting to "stable" (0.5.1) solved the issue.

just a quick browse through the commits brought up 5108c4635c847de9be0edadf572f7426f351b66a as a suspect but that's just guessing.

**Comment by samhed** [comment]
Hm, yes I can reproduce this problem easily:

* Disable the "Clip to window" setting in noVNC
* Connect to a session
* Make the browser window smaller than the session size or the session larger than the browser window
* If you use the scrollbars to view a part of the session which isn't the top-left corner the coordinates for the mouse events will be wrong.

 It only happens when we have scrollbars, and not while clipping is enabled.

**Comment by samhed** [comment]
Reverting 5108c46 does indeed fix this issue. This bug is a regression caused by #432
