### ISSUE TITLE
Blur not triggered when clicking in the canvas

### ISSUE THREAD

**Issue by ibc** [kanaka/noVNC#470]
Let's say I have the focus in a text input element (within a form, for example). Then I click into the canvas element, but there is no blur event in the text input. But if I click in any other element of the web page then the text input does loose the focus.

Of course I called `ungrab()` in the RFB's keyboard and mouse when I focus on the text input.

BTW: why is the canvas auto-focus so intrusive? shouldn't it just get the focus when it is clicked and (optionally) just if the mouse is over it?

**Comment by ibc** [comment]
Even worse, click outside the canvas does not fire "blur" event in the canvas element... Why is this so special?

**Comment by ibc** [comment]
I see that in both Keyboard and Mouse `this._target` is `document`. It may explain lot of things, right?

**Comment by ibc** [comment]
If I set `focusContainer` to the canvas element then it captures mouse events but does not capture keyboard events...

**Comment by ibc** [comment]
Confirmed that somehow the `grab()` method in the Keyboard and/or Mouse prevents "blur" to be fired in other elements when clicking into the canvas.

**Comment by ibc** [comment]
By removing the `Util.stopEvent(e)` call in `Mouse._handleMouseButton()` is behaves much better!

**Comment by ibc** [comment]
To summarize (sorry for so many comments):

* A common usage (IMHO) is to set `focusContainer` to the canvas element, so the user needs to click on it in order to send mouse/keyboard events to the VNC server.
* But it happens that `Mouse._handleMouseButton()` calls to `Util.stopEvent(e)` which means that:
   * No "blur" event will be emitted for the previously focused HTML element.
   * Cannot set a "click" event on the canvas element (this is, I cannot draw a red border on the canvas when it gets the focus).

By removing the `Util.stopEvent(e)` call in `Mouse._handleMouseButton()` that annoying behavior is fixed and things work as expected.

**Comment by kanaka** [comment]
@ibc this is a difficult one to get right for every situation. In the the common case where noVNC is the real element on the page, you want keyboard entry to send to vnc even when the mouse is not over the canvas. You also don't want to require click to focus because this will also send a vnc mouse click too which is not really correct (imagine you in a drawing program, or some other program where clicking has a behavior you might not want to do right then). You also definitely don't want to just disable stopEvent universally, because this will result in mouse events being handle by the page too. For example, triple clicking in the canvas (or clicking and dragging in the canvas) will then result in aras of the page outside the canvas getting selecting.

If you treat noVNC as a whole window application then I believe the current behavior is correct (and this is the closest analog to most native apps). If you embed it into an existing page, then the page and noVNC will have to coordinate on mouse and keyboard in whatever makes sense for that page. This is why the grab and ungrab hooks are exposed from noVNC.

**Comment by ibc** [comment]
You are right, the click on the canvas not only focuses the canvas element, but also sends such a click to the VNC server.

The `grab()`/  `ungrab()` methods are difficult to use. Basically to get the behavior I look for I should call ungrab() for any click or focus event in **any** other element of the page (but the canvas), which is specially complex and unfeasible if somebody is making a widget rather than a whole web app :)

I will try that, by default, the `focusContainer` does not capture events (so grab() is not internally called), and when click on it then it calls to grab(). IMHO such a first activation click should not be propragated.

**Comment by ibc** [comment]
Yep, that works. What was klilling me is the fact that the RFB automatically calls `grab()` for keyboard and mouse when it gets connected. IMHO it should be optional.

So I ungrab them and attach the following events to the canvas:

* onfocus:  do grab.
* onblur:  do ungrab.

In this way the activation click in the canvas generates "onfocus" but it is not sent via VNC.

**Comment by ibc** [comment]
It can be done by calling `ungrab()` for both keyboard and mouse once the "normal" state is emitted. No need for extra API.
