### ISSUE TITLE
errno 111, code 1006

### ISSUE THREAD

**Issue by screwballl** [kanaka/noVNC#493]
Running into an issue here. 
OS: CentOS 6.6
selinux active
novnc installed from EPEL
latest kanaka/noVNC from git as of earlier today
tigervnc-1.1.0-16.el6.x86_64 is installed and service is running
Ports:
viewer 5900
server 5901
I have tried swapping these but that doesn't help, just get other errors....

Yet every time I get this:
[root@sl6584 noVNC]# ./utils/launch.sh –-vnc localhost:5901
Using local websockify at /var/www/html/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /var/www/html/noVNC
  - SSL/TLS support
  - proxying from :6080 to localhost:5900

Navigate to this URL:

    http://sl6584:6080/vnc.html?host=sl6584&port=6080

Press Ctrl-C to exit

192.168.2.110 - - [09/Jun/2015 16:28:27] 192.168.2.110: Plain non-SSL (ws://) WebSocket connection
192.168.2.110 - - [09/Jun/2015 16:28:27] 192.168.2.110: Version hybi-13, base64: 'False'
192.168.2.110 - - [09/Jun/2015 16:28:27] 192.168.2.110: Path: '/websockify'
192.168.2.110 - - [09/Jun/2015 16:28:27] connecting to: localhost:5900
handler exception: [Errno 111] Connection refused

I've also tried via secure with the same problem.
Browser side (Firefox 25) I get Failed to connect to server (code: 1006)

I've tried 
./utils/launch.sh –-vnc localhost:5901
and
websockify --web /usr/share/novnc 6080 localhost:5901

But I get the same issues, just refuses to connect. With my VNC Viewer program I get unable to connect. I have tried it with Iptables ALLOW entries for those 2 ports, and also tried it disabled and still get the exact same errors.

Using the websockify on cli, it acts like it is starting but then get other errors:
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5901

 11: 192.168.2.110: "GET /favicon.ico HTTP/1.1" 404 -
 12: 192.168.2.110: Plain non-SSL (ws://) WebSocket connection
 12: 192.168.2.110: Version hybi-13, base64: 'False'
 12: 192.168.2.110: Path: '/websockify'
 12: connecting to: localhost:5901
then nothing.
Browser side it acts like it is connecting then I get "Failed to connect to server (code: 1000, reason: Target closed)"

Any help would be appreciated. - Mike

**Comment by screwballl** [comment]
/var/log/vnc.log shows:
UltraVnc Tue Jun  9 17:02:35 2015 > acceptConnection(): connection accepted ok from ip: 127.0.0.1
UltraVnc Tue Jun  9 17:02:36 2015 > openConnectionToVncServer(): can't resolve hostname:
UltraVnc Tue Jun  9 17:02:36 2015 > acceptConnection(): openConnectionToVncServer() failed

**Comment by samhed** [comment]
I didn't read everything, but I noticed you are using Firefox 25. I know we have had some issues with that particular version of FF (see #321 for example). Did you test with any other browser?

**Comment by screwballl** [comment]
Yes, I've tried with FF25, FF 38, and IE11, same problem, same errors on all browsers and multiple computers. I refuse to use chrome so that is not an option.

**Comment by DirectXMan12** [comment]
> Ports:
> viewer 5900
> server 5901

Just to clarify, you have your VNC server running on port 5901?  You listed "viewer" and "server" on two different ports above, which doesn't make much sense.

> With my VNC Viewer program I get unable to connect. 

So, you can't connect to your VNC server normally, either?

**Comment by screwballl** [comment]
Yes, in the configuration file, it lists those 2, so the server connections (like novnc) use 5901, and the viewer like TigerVNC Viewer is supposed to use 5900. I've tried the viewer program with both ports and neither works. I've tried novnc with both ports and neither works.

**Comment by screwballl** [comment]
No updates? No fixes? I assume this novnc project is abandoned then?

**Comment by kanaka** [comment]
@screwballl your last update sounded like you are having a general VNC issue rather than a noVNC issue (e.g. no viewer is able to connect). Lots of people use noVNC successfully all the time, so that also points to a likely configuration issue with your VNC server or how you are connecting to it. Do you have a reason to think this is noVNC or websockify related? Sometimes we are able to answer easy general VNC questions if the answer is fairly obvious from the information provided. You did a good job of providing lots of debug information, but it's not obvious to me what the issue is. You should focus on getting the plain vnc viewer working because until that works, noVNC/websockify don't have a chance of working.

**Comment by screwballl** [comment]
I tried it both ways, VNC enabled and disabled and get the same errors either way. I stopped vnc itself since all the documentation said vnc is not needed since websockify handles those connections natively. Using VNC to connect the server this is installed on (to view the desktop of the server itself) will not do any good since it is command line only server with no X windows desktop to share, thus the need for novnc acting like a repeater to relay the info from client to tech.

**Comment by kanaka** [comment]
@screwballl sorry, I didn't quire follow your last comment. In order for noVNC to work you need a VNC server running often on port 5900 or 5901 (if you already have an X server running). Then you need something translating between WebSockets that the browser speaks and normal TCP. That's where websockify comes in.  `./utils/launch.sh –-vnc localhost:5901` starts websockify listening on port 6080 (by default). When noVNC makes a websocket connection to port 6080, websockify will open a connection to port localhost:5901 and begin bridging/translating between the two. Note that some VNC servers have builtin websocket support (qemu and libvncserver based VNC servers), however tigervnc does not as far as I am aware.

But if you can't use a normal VNC client to connect to the VNC server, then there is no point in trying to get noVNC/websockify to do so because basic VNC needs to work first before noVNC/websockify has any hope of working.

**Comment by DirectXMan12** [comment]
closing due to no response

**Comment by brugnara** [comment]
I encountered this very same problem.

In my case, It was me. I forgot to start the VNC server it self....

Maybe this can help someone else looking for a solution.

Thank you for your effort, guys.
