### ISSUE TITLE
Could some one please help me?

### ISSUE THREAD

**Issue by Alfriadox** [kanaka/noVNC#521]
Hi, I'm a bit of a noob, but if someone would help me with this i would be thankful.

I followed the guide here:
 https://www.raspberrypi.org/forums/viewtopic.php?f=99&t=81165
to get this working on my raspberry pi, but every time I try to connect from my Chromebook at the URL it prints in the terminal, I receive 

" Server disconnected (code: 1006) " in a red bar in the top.

**Comment by kanaka** [comment]
@Alfriadox the message from the browser won't tell you much, what is needed for debugging this is the logs from the window where you are running websockify. It looks like those instructions have the proxy running in screen. So on your RPi if you run `screen -rx noVNC` that will be where the websockify logs messages are printed (Ctrl A-d to disconnect from screen).

**Comment by Alfriadox** [comment]
It is not working.

it returns `There is no screen to be attached matching noVNC.`

**Comment by Alfriadox** [comment]
I tried connecting again today.
I had the same error, but this time, in the ssh window i was running ./launch.sh in,

```
10.0.0.14 - - [21/Aug/2015 22:47:00] 10.0.0.14: Plain non-SSL (ws://) WebSocket connection
10.0.0.14 - - [21/Aug/2015 22:47:00] 10.0.0.14: Version hybi-13, base64: 'False'
10.0.0.14 - - [21/Aug/2015 22:47:00] 10.0.0.14: Path: '/websockify'
10.0.0.14 - - [21/Aug/2015 22:47:00] connecting to: localhost:5900
handler exception: [Errno 111] Connection refused
```
popped up.

**Comment by kanaka** [comment]
@Alfriadox that's what I suspected. The problem is not between the browser and websockify, but rather exists between websockify and the VNC server. The error is indicating that websockify attempted to connect to localhost:5900

I also note that the RPi configuration here https://dl.dropboxusercontent.com/u/14125489/RaspberryPi/vncproxy has websockify configured to connect to localhost:5901 rather than localhost:5900 so maybe you are running an old version of something.

**Comment by DirectXMan12** [comment]
Were you able to get things working, @Alfriadox ?

**Comment by Alfriadox** [comment]
No but I found a chrome web store app for vnc.
