### ISSUE TITLE
Black & blue blocks doodling all over the canvas when connecting to QEMU  

### ISSUE THREAD

**Issue by dwang2** [kanaka/noVNC#531]
![doodling](https://cloud.githubusercontent.com/assets/2972354/9993362/56f9ea7e-6045-11e5-8275-e9e4fd8c6b70.png)

We've been struggling the issue for a week as we connect noVNC to QEMU(1.6.2) of XEN (4.4.0) in CentOS 6.5 minimal. We saw black and blue blocks smeared all over the canvas especially when cursor was moving. I'm using noVNC from the master branch. Please help!

Data URI scheme cursor supported
util.js:216 Using native WebSockets
util.js:218  Msg: noVNC ready: native WebSockets, canvas rendering
util.js:218 
util.js:216 connecting to wss://10.71.119.240:6081/websockify/?token=-1
util.js:216 Detected binaryType support in WebSockets
util.js:216 Server choose sub-protocol: binary
util.js:218  Msg: Starting VNC handshake
util.js:216 Server ProtocolVersion: 003.008
util.js:218  Msg: Sent ProtocolVersion: 003.008
util.js:218  Msg: Authenticating using scheme: 2
util.js:218 
util.js:218  Msg: Authentication OK
util.js:218  Msg: Authentication OK
util.js:216 Screen: 640x480, bpp: 32, depth: 24, big_endian: 0, true_color: 1, red_max: 255, green_max: 255, blue_max: 255, red_shift: 16, green_shift: 8, blue_shift: 0
util.js:218  Msg: Connected (encrypted) to: QEMU (user-image)
util.js:216 First FBU latency: 507
util.js:216 Timing of full FBU, curr: 94, total: 94, cnt: 1, avg: 94
util.js:216 full FBU round-trip, cur: 708, total: 708, cnt: 1, avg: 708

**Comment by DirectXMan12** [comment]
Can you clarify which browser you're using?  Also, since you're using master, can you indicate which commit you're using?

**Comment by dwang2** [comment]
I am using commit 40b35fa20d459c731a5de826f4bd17634101a1db. Also, I tested it with Chrome 44.0.2403.157 and IE 11.0.9600.17842.

**Comment by DirectXMan12** [comment]
To help narrow down the potential causes, does it work with the current release of noVNC? (or any commit at or before 8f3c0f6b9b5e5c23a7dc7e90bd22901017ab4fc7)?

**Comment by aderumier** [comment]
Hi,
we have seen exactly same artifacts when we have tried to integrated last novnc with proxmox 4.0.
This is since https://github.com/kanaka/noVNC/pull/488 .
We have seen this with chrome,firefox,ie    linux && windows.


We have reverted to https://github.com/kanaka/noVNC/commit/8f3c0f6b9b5e5c23a7dc7e90bd22901017ab4fc7  , and it's working fine.

**Comment by DirectXMan12** [comment]
ok, thanks.  That's quite helpful.  Depending on how busy I am over the next couple of weeks, I'll try and reproduce.  Since we now have a work copy of `vnc_playback.html`, a websockify recording of a session with the issue would help greatly (you can do this by running websockify itself with with `--record somefile.js`, but you have to run it directly instead of via `launch.sh`).  You can send the recording directly to me if you can't/don't feel comfortable posting it elsewhere (it may be large).

**Comment by DirectXMan12** [comment]
I *think* I was able to reproduce the issue on my current machine.  The PR above should fix your issue (essentially, we were only using the first buffer that Pako decoded, whereas Pako was expecting us to run it in a loop if the output buffer was too small.  Previously, I had tested with VNC servers that sent compressed rects whose output size was < 100KiB, so we didn't hit the issue.  The new code should resize as necessary -- I remember meaning to put that in, but it must have somehow gotten misplaced).

@aderumier @dwang2 please let me know if the above PR fixes you issues.

**Comment by dwang2** [comment]
Tested commit 6fc9884b2ce20b978da80c3d69b7e40095b3a1b0 and it fixes the issue. Thanks!

**Comment by aderumier** [comment]
Hi,
This fix the issue too . Thanks !
