### ISSUE TITLE
Adding a property for disabling the this._fail("Disconnect timeout");

### ISSUE THREAD

**Issue by computate** [kanaka/noVNC#540]
To whom it may concern:

I love the work you have done with noVNC and it is an important tool for us. I would like to contribute a solution to make configurable the this._fail("Disconnect timeout"); This is because I handle the shutdown of our virtual machines in our backend application and the setTimeout of this._disconnectTimeout*1000 causes a problematic flicker in our virtual machines 3 seconds after our machines are already shut off. Please let me know if you would consider this if I make it a pull request for you.

Please consider adding the following property:

```javascript
            ['reconnect', 'rw', 'bool'],            // Whether or not to reconnect after disconnection
```

And the following default property:

```javascript
            'reconnect': true,                      // Whether or not to reconnect after disconnection
```

And the following modification to the code in the _updateState function under "switch (state) {":

```javascript
                case 'disconnect':
                    if(this._reconnect) {
                        this._disconnTimer = setTimeout(function () {
                            this._fail("Disconnect timeout");
                        }.bind(this), this._disconnectTimeout * 1000);
                    }
```

Thank you for your consideration.

Respectfully,

Christopher Tate

**Comment by DirectXMan12** [comment]
Hi!  Thanks for the patch.  Can you clarify the issue?  What do you mean "a problematic flicker"?  I'm just trying to understand the context for this patch.

**Comment by computate** [comment]
We use the onUpdateState callback to show the canvas when the state is 'normal'. When a machine is shutdown, noVNC changes the state to 'failed' and we use the onUpdateState callback to show a "Could not connect" background. The _updateState function sets a timeout for 50 ms to change the state to 'disconnected' and we show a "Machine powered off" background. 

Here is where the flicker comes in: 3 seconds later due to the disconnectTimeout, which calls the _fail function, the state is changed to 'failed' again  and we show a "Could not connect" background again and 50 ms the state changes to 'disconnected' and we show again a "Machine powered off" background. This is why we would like to disable the disconnectTimeout in our situation.

**Comment by kanaka** [comment]
@computate reconnect logic should really be done at a higher level since it's really a policy decision for the integrator of noVNC. We sort of support a standalone mode in the case of vnc.html, but really noVNC as a project should try and avoid making policy decisions as much as possible. Giving the right hooks so that integrators can easily drive it via their own policy model is definitely a goal. And given that the fail/disconnect states are complicated, it's certainly possible you've experience a bug or limitation in how states are reported. However, the change you suggest appears to be a partial reconnect implementation rather than a fix to state handling to support your system.

Can you show the onUpdateState states you are getting and what you are expecting to see?

**Comment by kanaka** [comment]
Just to clarify, here is an example why reconnect policy should stay out of noVNC: the integrators of noVNC often have a higher level application that uses a standard RESTful communication channel that temporarily opens a websockify port to the specific noVNC client and target. Automatic reconnect in noVNC would not be appropriate because it will always fail in that scenario. The correct thing is for noVNC to notify the higher level of a disconnect, then the higher level can re-setup the authorization, and then call into noVNC again (probably by recreating the RFB object) in order to connect again.

**Comment by DirectXMan12** [comment]
@computate maybe I'm missing something here, but the `disconnectTimeout` should only trigger on a state of `'disconnect'` *not* `'disconnected'` -- if noVNC loses the connection, you get `failed -> disconnected`.  On the other hand, if you manually select "Disconnect", you get `disconnect -> [set timer] --[if the browser fails to actually disconnect]--> fail -> disconnected`.  Is the issue that you have someone pressing disconnect, and then before the disconnection happens the machine shuts down?

**Comment by DirectXMan12** [comment]
Closing due to no response
