### ISSUE TITLE
Not able to connect on Wii U browser with various error codes; crashes web browser

### ISSUE THREAD

**Issue by randomouscrap98** [kanaka/noVNC#549]
I know the Wii U is probably on the bottom of your compatibility list, but I wanted to report the issue anyway. The Wii U browser supports websockets and the canvas, and I've definitely used websocket applications on it before (stuff like websocket chatrooms, etc.). However, when I try to connect with noVNC, the mini webserver gives various errors. Usually when connecting the first few times, it gives errors like ```handler exception: [Errno 107] Transport endpoint is not connected```. The console on the Wii U gives an error: ```WebSocket network error: error code -1```

![error -1](https://db.tt/ZAzlDu53)

There is also some "forever pending" network activity even after the websocket is closed (this is after trying the connection again to show the pending activity; this is why there's two):

![network](https://db.tt/f3dsebr1)

Those . appear to be trying to access ws://., which I assume occurs after it tries to switch protocols. Then, after a few tries, you sometimes get a mini webserver error: ```code 400, message Bad request syntax ('\x88\x80\xb8\xd6\x18z')```, and the Wii U gives this:

![disconnect](https://db.tt/sYYhTM6J)

Finally, if you close the Wii U web browser after trying to connect, it simply hangs forever. The Wii U becomes unresponsive, and the only option is to force the system to shutdown. I'm guessing it has something to do with that glitched out pending connection.

I don't think this has anything to do with noVNC, but rather with the Wii U's implementation of websockets. It looks like you switch to some binary sub-protocol... IDK if that's the issue and the Wii U's implementation of that is broken, or if it has something to do with the pending connection to ws://., or if they're related. I know that plain old (I assume text-based) websockets run fine on the Wii U; maybe there could be (or already is) a way to force disable the binary sub-protocol with a GET parameter? I'm sorry; I'm familiar with websockets on a "yeah I've used them" level, but I don't know this much about them.

Edit: forgot to mention that noVNC works fine on all my other devices; thank you!
Edit2: It works fine on the Wii U when using [novnc.com](novnc.com); this problem only seems to happen with the local mini webserver.

**Comment by DirectXMan12** [comment]
It's possible that the Wii U's browser doesn't support binary WebSockets (WebSockets have two modes: text, which used to be used as the transport for base64 noVNC, and binary, which is used currently as the only supported mode in noVNC).  We dropped support for base64 WebSockets in one of the more recent patches since they were adding a bunch of overhead, but didn't provide much for modern browsers.  Unfortunately, I'm unable to test this theory (since I do not have a Wii U).  Please let us know if you figure something out.

**Comment by silentcenturion** [comment]
I have a similar problem when trying to make the following connection:

**Client1** - Win10  x64 - Awesomium (32-bit) browser for Unity-3D (32-bit executable, since Awesomium, which is based on Chromium, does not support x86_64 on Windows)
**Client2** - Same machine as above, except using Chrome
**Server** - Debian running x11VNC and noVNC/utils/launch.sh

Client 2 connects with no problems and similar performance to the dedicated realVNC client.
Client 1 fails with "handler exception: [Errno 107] Transport endpoint is not connected"

I guess I'm SOL if Awesomium/Chromium are stuck on base64 WebSockets... :/

**Comment by DirectXMan12** [comment]
Chromium should work fine (that's what I use).  What build of Chromium is Awesomium based on?
