### ISSUE TITLE
Password for accessing 

### ISSUE THREAD

**Issue by sonkengmaldini15** [kanaka/noVNC#561]
Hi, 
I want to connect myself to the panel please where is the password to provide ?

**Comment by DirectXMan12** [comment]
err... what do you mean?

**Comment by sonkengmaldini15** [comment]
When i run the nvc.html it asks me a password i wonder where i can find it

**Comment by DirectXMan12** [comment]
The password is whatever you have set on your VNC server.

**Comment by sonkengmaldini15** [comment]
I don't know well VNC but i want to test the project please tell me what are quick requirements for getting started .

**Comment by DirectXMan12** [comment]
For noVNC, you have to have a VNC server, an browser to access vnc.html, and potentially an instance of websockify (if you use TigerVNC as your VNC service, this is not necessary, as it can speak WebSockets.  Otherwise, you'll need websockify to proxy normal TCP socket traffic to WebSocket traffic).  Generally, VNC servers serve traffic on ports 5900+ (VNC "port" :0 is 5900, :1 is 5901, and so on).  Websockify proxies this traffic to a specified port (by default, 6080).  You can then connect noVNC to port 6080 to access you VNC server.

Some VNC servers support authentication.  If you're being asked for a password, this probably means whatever you are using has authentication.  That would be something you set up (or something that's default on your VNC server).

**Comment by sonkengmaldini15** [comment]
Is it only works on Linux and his distributions ?

**Comment by DirectXMan12** [comment]
websockify itself has some issues on Windows right now, but it should run on *NIX distributions (BSD, Linux, OSX, etc) fine.  noVNC is platform independent, and there are VNC servers for just about any platform under the sun.

**Comment by 9sdf** [comment]
why did you close it
