### ISSUE TITLE
Rendering artifacts in firefox

### ISSUE THREAD

**Issue by qv-8942** [kanaka/noVNC#571]
Setup:
- Browser: Firefox 43 (both @ Windows / Linux), current Chromium and Opera seem not to be affected
- TightVNC Server for Windows 2.7.10, same issue with UltraVNC Server

The origin of the issue seems to be commit abf2b09. I connected three different versions of the noVNC client simultaneously and moved the foreground window around. While a825582 behaves properly, a369a80<sup>1</sup> and 670dbdd<sup>2</sup> show rendering artifacts:

<sup>1</sup> *some commits after abf2b09 since while doing the test, abf2b09 lost connection shortly after being established.*
<sup>2</sup> *current head@master*

![novnc-bug](https://cloud.githubusercontent.com/assets/16468678/12536395/c9a7326e-c2a3-11e5-9916-768f374c5212.png)

**Comment by cavac** [comment]
I can also reproduce the problem here, tested with Linux and Windows. I'm using my own Webserver/Websocket proxy, so i'm pretty sure it's not a server side problem.

![firefox_novnc_artifacts](https://cloud.githubusercontent.com/assets/784308/12784137/ac9a1c4c-ca85-11e5-81a6-658ecc7314e5.png)

**Comment by cavac** [comment]
The bug seems to be limited to Firefox. Could this be a Firefox problem? I've found this post here:

[https://www.reddit.com/r/firefox/comments/426scl/bug_firefox_ui_and_canvas_artifacts_if_too_many/](https://www.reddit.com/r/firefox/comments/426scl/bug_firefox_ui_and_canvas_artifacts_if_too_many/)

Maybe it's not really the number of tabs but the number of screen updates/drawing operations per second?

There were also a few other reports of rendering artifacts in Firefox over the last few years, for example:

[https://support.mozilla.org/en-US/questions/1071126](https://support.mozilla.org/en-US/questions/1071126)

[https://github.com/playir/playir/issues/150](https://github.com/playir/playir/issues/150)

**Comment by qv-8942** [comment]
It is not a Firefox-only issue. I can reproduce it with Opera 12.16<sup>1</sup> as well:

<sup>1</sup> _The last version based on their own rendering engine "presto"_

![opera-v12 16](https://cloud.githubusercontent.com/assets/16468678/12898808/d4a77b58-ceae-11e5-9878-542d34c5729e.png)

**Comment by samhed** [comment]
I have never seen this problem. @cavac have you seen the issue both with a Linux and a Windows server? Or are you saying that you tested with both Linux and Windows clients? All the screenshots in this thread show Windows desktops

**Comment by cavac** [comment]
@samhed The issue is present on both Windows and Linux versions of Firefox.

VNC Server is TightVNC 2.7.10 in this test. Google Chrome seems to work without problems.

Also, I'm reasonably sure it's not a problem with the VNC<->Websocket proxy (i'm using my own implementation, not the default one).

![vnc_tearing_problems](https://cloud.githubusercontent.com/assets/784308/12944365/d9072af2-cfe6-11e5-8aeb-ea2c9a5aff10.png)

**Comment by samhed** [comment]
Yes, I don't believe the operating system on which you run Firefox is relevant. I think this is an issue with the TightVNC server for Windows. I don't understand why you say this:

> i'm pretty sure it's not a server side problem.

When you haven't tested different servers? You are running the exact same VNC server as @qv-8942 . I don't see any reason to why this would NOT be a server sider problem.

**Comment by samhed** [comment]
@DirectXMan12 have you been able to reproduce this?

**Comment by cavac** [comment]
Well, it worked with the same TightVNC servers with older versions of noVNC. Also, it works without problems if i use Google Chrome. It also works with the "vncviewer" command on Linux.

Can i turn on some option to give me more debug info in the browser console (e.g. which encoding and color depth is used in the connection)?

**Comment by samhed** [comment]
Ok!

Yes, you can turn on debug-logging at the bottom of the settings, here:

![screenshot from 2016-02-10 16-28-17](https://cloud.githubusercontent.com/assets/4117162/12951609/63cf92b0-d013-11e5-995a-d2e63fc36700.png)

**Comment by cavac** [comment]
I've been playing around for a while with my setup here and have a few more observations. 

First, to clarify (this may or may not be important, see bellow), my TCP<->websocket proxy does NOT parse the VNC protocol, it just forwards data when it arrives. So there are possible a lot of websocket messages that do NOT match RFB frames.

- I was able to observe the tearing problem in Google Chrome as well, but this is a very seldom occurence and has proven impossible to re-create in a reliable way.
- Commenting out the "['TIGHT',               0x07 ]," line in rfb.js solves the problem in Firefox, at the cost of speed
- When changing the windows size in my proxy (max. amount of bytes to send in a websocket frame), i get the impression that the "pattern" of the artifacts change
- The artifacts are not completly random, this looks like decompression errors. 
- There doesn't seem to be random colors. It looks like the colors still correspond to stuff shown on the screen, just with the pixel locations shuffled around.

I get the distinct feeling, that while noVNC itself handles incomplete frames (one which are split over multiple websocket messages) correctly (indication: the connection itself keeps working, disabling tight compression solves all visual problems), the decompression algorithm for TIGHT compression behaves poorly when decompressing incomplete frames.

I don't understand how this is implemented - my internal knowledge of noVNC is rather limited. But i'll hazard a guess that noVNC tries to decompress incomplete frames (which trips of the zlib), instead of waiting for a complete frame to arrive and then decompress it all at once.

**Comment by DirectXMan12** [comment]
Does your WebSocket proxy have a way to record a session -- if you could record the websocket frames that it's sending, we could use that to reproduce on our end (in websockify, for instance, the `--record` option can be used to achieve this).

We did switch zlib implementations in the PR that you referenced (as the old one was horribly slow), so it's possible the zlib implementation is doing something incorrectly (or the old implementation handled partial frames better).

**Comment by cavac** [comment]
I just added a way to record a session. Couldn't find the exact format definition, so i recorded a test session with websockify and sort of reverse engineered by eye and then checked it against vnc_playback.html.

[vncrecord.dat.zip](https://github.com/kanaka/noVNC/files/144141/vncrecord.dat.zip)

I also recorded a video of this very session for reference. First, i record the session in Firefox, then play it back in Firefox and Chrome:

[https://youtu.be/uqnfx1I6i74](https://youtu.be/uqnfx1I6i74)

The thing i noticed is that playing back the same file in Chrome seems to be fine (although i know that there can be permanent artifacts in Chrome as well).

Could this be a timing problem, you know, like the next javascript callback triggering before the first one is complete? Or some sort of browser dependent bug, like Chrome initializing an array different than Firefox (zeroed vs. non-zeroed)?

**Comment by cavac** [comment]
Another curious observation i noticed by accident:

When i use vnc_playback.html, it defaults to 3 Iterations. The rendering artifacts are only visible during the first iteration in Firefox.

I also did a second, slightly longer, recording session using different programs on the remote computer. Just to make sure Windows Explorer isn't somehow the culprit.

[vncrecord2.dat.zip](https://github.com/kanaka/noVNC/files/144215/vncrecord2.dat.zip)

[https://youtu.be/0Yy2CN-GPZc](https://youtu.be/0Yy2CN-GPZc)

**Comment by cavac** [comment]
Here's a bunch of longer recording session. I noticed that that on the first recording session, only the first iteration of playback showed artifacts.

With this recording session (bigger screen), i get artifacts on all playback iterations in Firefox.

Also, when i set "true_color: false", the artifacts seem to go away (i suspect they will return on higher resolutions or something).

The files are a bit large for the github bugtracker, so i uploaded them to my website:
https://cavac.at/admin/pimenu/download/vncrecord_long.zip (3 sessions, ~32 MB).

If you need to add one or more of the recording session files to your project for regression testing in the future, you are free to do so.

**Comment by DirectXMan12** [comment]
Thanks, I'll try and investigate today.

**Comment by kanaka** [comment]
@DirectXMan12 that sounds suspiciously like a rendering queue issue if multiple playbacks of the same data are getting different results (and Chrome seems correct most of the time). It could also be a bug in firefox (such as the onload for an image firing before the image is actually fully rendered).

**Comment by DirectXMan12** [comment]
@kanaka: that's my suspicion as well.  I've added in some draw tracing code, and it seems like all of the distortion comes from a particular type of draw method.  I haven't had a chance to look further, but I'm going to try to get to it soon

**Comment by DirectXMan12** [comment]
@cavac I've opened a PR, which I'll try and merge tomorrow unless I get any strenuous objections from the other maintainers ;-).

**Comment by DirectXMan12** [comment]
Fix is merged.  Let me know if you have any further issues!

**Comment by qv-8942** [comment]
The artifacts are gone. Thanks!

**Comment by cavac** [comment]
I agree, this seems to have fixed it!

@DirectXMan12  @kanaka  Very nice work! You just saved my weekend :-)
