### ISSUE TITLE
AWS Load Balancer -- Too Many Redirects

### ISSUE THREAD

**Issue by trevorphillipdavis** [kanaka/noVNC#578]
Using Cendio ThinLinc, which leverages this project.  I have the SSL termination on a load balancer in AWS, behind the load balancer have server running.  Getting too many redirects.  I believe this is because the server behind the load balancer is forcing https, but i'm trying to use http.  

If I don't use http behind the firewall and try to use https all the way through the server behind the load balancer disconnects the session immediately.

**Comment by samhed** [comment]
I have personally never used Amazon Web Services' load balancer, but I assume you are using reverse proxy? If so, I would believe this is where your problem lies. We have seen the "too many redirects"-issue before with ThinLinc and reverse proxy, the issue is usually that your reverse proxy is setup the wrong way. When using ThinLinc's HTML5 client (which is using noVNC) you will have to make sure that all the redirects work correctly, else you might end up in a redirect loop.

Firstly, the HTML5 client uses URL:s with paths that start with /websocket and /main. / redirects to /main/. Make sure your proxy knows Websockets. Secondly, authentication to ThinLinc happens in two phases. It begins with authenticating with the ThinLinc master server, which chooses an agent server for the session. Then it authenticates with the ThinLinc agent server that was chosen. Thus, the browser can be redirected to a different machine after authenticating with the master.

Note: Make sure to set /vsmagent/agent_hostname to a hostname that is reachable from your master as well as your clients.

I don't know if this is helpful to you; But I know that we have had people successfully using nginx, for example:
https://www.verboom.net/blog/index.html?single=20151019.0

And lastly, ThinLinc does not support unencrypted connections.
