### ISSUE TITLE
Please allow to use both local and remote cursor at the same time

### ISSUE THREAD

**Issue by patrakov** [kanaka/noVNC#590]
(this may well be an issue that is better solved in x11vnc, I don't know)

The use case is: we run x11vnc over Xdummy, and noVNC over it. We have several connections to the same VNC display. The purpose is that one person explains how to use the software that is running inside the VNC session to others, who watch and sometimes try things out (point to various items, click, type, ...).

I want each participant to see only the local cursor if he/she was the last person who moved the pointer. But if someone else move it, then both local and remote cursors should be shown, so that the person can both see where that other person wants to click, and where the local pointer is (for further clicking).

**Comment by DirectXMan12** [comment]
So, you could certainly override the cursor code to show both cursors.  However, if you wanted to achive what you want, you'd probably also have to modify the `onMouseMove` handler in `rfb.js` (`_handleMouseMove`), since otherwise the current "passive" viewers would also send mouse move events.

I'm not sure this is really appropriate for mainline noVNC, but I'd certainly be willing to answer any questions about customizing noVNC.
