### ISSUE TITLE
Allow skipping security handshake

### ISSUE THREAD

**Issue by rgerganov** [kanaka/noVNC#643]
Currently in OpenStack there are two ways for using noVNC with VMs running on VMware ESX:

1)
- allocate VNC port number for each created VM
- modify ESX firewall to allow the allocated VNC ports
- use nova-novncproxy to create websockets from TCP sockets

2)
- obtain MKS ticket for the VM
- connect to ESX:902 and present the MKS ticket; this creates "authenticated" VNC socket for the given VM
- use [nova-mksproxy](https://github.com/openstack/nova-mksproxy) to create websockets from the authenticated sockets

The second option is **much** better than the first one because it doesn't require any networking changes on the hypervisors (works out of the box).  It also doesn't require dynamic port allocation which is very tricky in OpenStack running on top of vSphere.

For the second option to work, I have forked [noVNC](https://github.com/rgerganov/noVNC) and [skipped](https://github.com/rgerganov/noVNC/commit/cb7f47a0e5fe27ed24eeab28ba4d715a6f351937) the authentication part of the protocol.  It'd be really nice if there is a parameter/option in noVNC which disables the security handshakes and goes straight to 'ServerInitialisation'.  Would you accept a patch in noVNC which adds such an option?

**Comment by DirectXMan12** [comment]
Can you provide a link to documentation about the MKS protocol?  It seems like you've also commented out version negotiation.  While I'm generally inclined to support different platforms, just providing an option to skip the beginning of the VNC negotiation phase seems a bit sub-optimal.  Is there a way we can detected an MKS server instead?  Alternatively, since you're effectively doing part of the negotiation in the proxy, could you fake VNC replies to the client (send your appropriate verison + the "no auth" option)?

**Comment by rgerganov** [comment]
Unfortunately I cannot provide any public documents for the MKS protocol.  However, I like the idea to return fake VNC replies from the mksproxy.  I will explore this option for now.  Thanks a lot!

**Comment by DirectXMan12** [comment]
No problem.  Let me know if you have any issues.  There should be a Nova PR from me that does something similar for proxy-to-VM encryption purposes hanging around the OpenStack gerrit somewhere.

**Comment by satwikk** [comment]
@rgerganov How can I setup mks connection by hosting noVNC on my local machine? I am not able to establish ws connection with esxi host when I use "localhost/noVNC" instead of "https://rgerganov.github.io/noVNC/6/". When I use your github noVNC link, I am able to establish a mks connection with ESXi 6 host (for which there is no need to run websockify proxy), but not able to do the same with "localhost/noVNC". Please assist with this!

**Comment by rgerganov** [comment]
There are examples for both ESXi 5.x and ESXi 6 at https://github.com/rgerganov/mks
I suggest to open an issue there if it doesn't work for you.

**Comment by satwikk** [comment]
@rgerganov No luck, I have opened an Issue in https://github.com/rgerganov/mks.
