### ISSUE TITLE
Start and stop noVNC via xinetd

### ISSUE THREAD

**Issue by NewCorn** [kanaka/noVNC#647]
Hey,

I'm not quite sure if I post this in the right form, or it's actually allowed to post anything like this here.
Nevertheless, I'll explain my problem in short:

I've got a running VNC server on my host system. And I would like to setup another server running my xinetd to autoconnect with any workstation to this VNC Server on the host.
So far, I've rewrote the VNC file in /etc/xinetd.d, which looks like the following:

```
service vnc1
{
        type            = UNLISTED
        port            = 5906
        socket_type     = stream
        protocol        = tcp
        wait            = no
        user            = root
        server          = /tmp/noVNC/utils/launch.sh
        server_args     = --vnc xxx:5906
        disable         = no
        log_type        = SYSLOG daemon debug
}
```

Alright. My problem now is, that I may connect via any browser and workstation to this server, while first open up a connection like xxx:5906 in one browser tab, and then run 

> http://xxx:6080/vnc.html?host=xxx&port=6080&password=123&autoconnect=true

This works for me well.
But I am not able to figure out, how I can kill the script afterwards. Because my problem is, after I've opened this "session", it runs forever end blocking the port 6080. Therefore I am not able to connect with any client afterwards to the server.

I've tested so far the "wait" argument in xinetd, which does not work for me at all, if I set it to yes.
Also I found no way to "press" CTRL + C, which would stop the script, because my solution was just to get any connection to the port to make xinetd run via the browser.
I've forgot to mention, that my only workarround was to restart xined with 

> systemctl restart xinetd

which actually would kill all sessions, not only the one.
I appreciate any help!

**Comment by kanaka** [comment]
I would recommend running websockify directly instead of using the launch.sh wrapper script (which just runs websockify with some default arguments). Then you can pass the --run-once flag to exit after each connection. Also, you probably want to run websockify on the same port as your xinetd service configuration so that you can just connect directly to it once.

However, once you do that, you probably want to run a dedicated web server to server, because websockify will shutdown after every request (including each web request) will will really slow down loading the initial page and cause unnecessary load.

So your xinetd service would look something more like this (I haven't tested this but you should get the general idea):

```
service vnc1
{
        type            = UNLISTED
        port            = 5906
        socket_type     = stream
        protocol        = tcp
        wait            = no
        user            = root
        server          = /tmp/websockify/run
        server_args     = --run-once 6080 xxx:5906
        disable         = no
        log_type        = SYSLOG daemon debug
}
```

Now, assuming you have a web server at port xxx:8080, you would browse to:

`http://xxx:8080/vnc.html?host=xxx&port=5906&password=123&autoconnect=true`
