### ISSUE TITLE
Customize the HTML page

### ISSUE THREAD

**Issue by geostant** [kanaka/noVNC#691]
Hello,

I'm using your noVNC on a system that I build (combining it with a desktop docker container).
I would like to customize a few issues and couldn't find it in any documentation:
- Automatically resize the VNC screen to match the browser size (this is top priority)
- Remove the top command bar (shutdown, reboot, etc...) 
- Remove the black bottom bar

Any reference on how to achieve that ?

Thanks

**Comment by samhed** [comment]
We do not have any documentation for how to customize your own noVNC.

> Automatically resize the VNC screen to match the browser size (this is top priority)

noVNC already has functionality for this, see the setting for 'Scaling Mode'. However note that if you want to resize a desktop or application on the server-side, your VNC server has to support his as well. One example of a VNC server that supports remote resize is tigervnc.

> Remove the top command bar (shutdown, reboot, etc...)
> Remove the black bottom bar

I assume that you have been looking at vnc_auto.html. I would recommend you to try out vnc.html instead since it contains a lot more features. The interface in vnc_auto.html is very old and outdated,personally I woulnd't mind retiring it.

**Comment by geostant** [comment]
Cool, thanks for the info.

I've tried vnc.html instead of vnc_auto.html, however with vnc.html the connection isn't automatic
and require the user intervention (instead of the auto mode which is more suitable for my application).

Another issue that I noticed is the the browser height is extremely long and contain repeatable partial elements from my session.

**Comment by samhed** [comment]
> I've tried vnc.html instead of vnc_auto.html, however with vnc.html the connection isn't automatic
and require the user intervention (instead of the auto mode which is more suitable for my application).

You can add ?autoconnect=true to the url. Or, since you are looking to use a modified version anyway, you can just modify the code in app/ui.js:

https://github.com/kanaka/noVNC/blob/master/app/ui.js#L109

> Another issue that I noticed is the the browser height is extremely long and contain repeatable partial elements from my session.

Interesting, this sounds like the same issue that @boistordu is running into in #672 could you open a new issue for this?

**Comment by DirectXMan12** [comment]
> The interface in vnc_auto.html is very old and outdated, personally I woulnd't mind retiring it.

@samhed: For future reference OpenStack uses `vnc_auto.html`, so we need to keep it working, and/or work with them to figure out a good solution for them ;-)

**Comment by samhed** [comment]
@DirectXMan12 good point, opened #695 for a discussion
