### ISSUE TITLE
Mouse cursor hidden when connecting to QEmu VNC display

### ISSUE THREAD

**Issue by kouhj** [kanaka/noVNC#726]
noVNC version v0.6.1.

I setup a Ubuntu 14 guest with QEmu/KVM on Ubuntu Xenial host, and the guest display is thru VNC.
When I accessed the guest display with noVNC, the mouse cursor was automatically hidden when I moved the mouse into the display area, but the guest OS was responding correctly to the mouse movements or clicks, just that I was unable to see the mouse cursor :-(
I tried to access VNC directly with TightVNC viewer, the native cursor is shown correctly. 
If I show TightVNC session and noVNC session side by side at the same time, still cursor is only visible in the TightVNC window.
It seems noVNC hides the mouse cursor under some conditions?

**Comment by samhed** [comment]
Thank you for testing another VNC client, it is very often a good thing to test first. What browser are you using? Could you try the latest master of noVNC? Is the setting "local cursor" enabled or disabled?

**Comment by kouhj** [comment]
Cool. Enabling "local cursor" with latest master fixed it! Thanks!
The same trick does not work for v0.6.1. Although the mouse is shown, there is no any mouse interaction with the remote desktop.

**Comment by samhed** [comment]
Nice that you got it working for you. It's however a bit puzzling since at a quick glance I don't think that we have changed any code with regards to cursors since v0.6.1.. I don't have the time to look further into this though. Feel free to try and see which commit it was that fixed this for you:

https://github.com/kanaka/noVNC/compare/v0.6.1...master

Anyway, I'm closing the issue
